FROM python:3.10-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Install MLflow and S3 dependencies
RUN pip install --no-cache-dir mlflow boto3

WORKDIR /mlflow

# Expose port
EXPOSE 5000

# Default command (can be overridden in docker-compose)
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]
